### ISSUE TITLE
Values False/True wrong!

### ISSUE THREAD

**Issue by kolarzjulian** [google/cbortree#4]
Hello,
I just recognized, that the cbor values for True and False are wrong.
In the file CborSimple.java:
/**
     * Additional data value that represents "true" when used with {@link CborMajorType#OTHER}.
     *
     * @see #getValue()
     * @see #TRUE
     */
    private static final int TYPE_TRUE = 20;

    /**
     * Additional data value that represents "false" when used with {@link CborMajorType#OTHER}.
     *
     * @see #getValue()
     * @see #FALSE
     */
    private static final int TYPE_FALSE = 21;

According to the Cbor Spec it should be exactly the opposite:
TYPE FALSE = 20;
TYPE TRUE = 21;
see: https://en.wikipedia.org/wiki/CBOR 
Simple value | Semantic
-- | --
20 | Boolean false
21 | Boolean true
22 | Null
23 | Undefined

**Comment by darconeous** [comment]
How utterly embarrassing! I'm not sure how I missed this.

**Comment by AndrewWestberg** [comment]
Any ETA on this?

**Comment by AndrewWestberg** [comment]
https://github.com/google/cbortree/pull/5

**Comment by AndrewWestberg** [comment]
This fix has been merged awhile ago. @darconeous, can you bump the version and get a build published to Maven Central for this?

**Comment by darconeous** [comment]
Published
